gallery/gallery/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gallery/store/urls.py
from django.urls import path
from . import views

urlpatterns = [
	path('', views.store, name="store"),
 	path('store/', views.store, name="store"),
	path('cart/', views.cart, name="cart"),
	path('checkout/', views.checkout, name="checkout"),
 	path('location/', views.location, name="location"),
	path('collections/', views.collections, name="collections"),
	path('contacts/', views.contacts, name="contacts"),
 	path('about/', views.about, name="about"),
  	path('news/', views.news, name="news"),
  
 	path('update_item/', views.updateItem, name="update_item"),
  	path('process_order/', views.processOrder, name="process_order"),

#uTo-code
	path('home/', views.home, name='home'),
    path('profile/', views.profile, name='profile'),
    path('login/', views.login_user, name='login'),
    path('register/', views.register_user, name='register'),
    path('logout/', views.logout_user, name='logout'),
#/uTo-code
]

gallery/store/models.py
from sre_constants import CATEGORY
from django.db import models
from django.contrib.auth.models import User


class Customer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField(max_length=200, null=True)
    email = models.CharField(max_length=200, null=True)

    def str(self):
        return str(self.name)
    
class Product(models.Model):
    name = models.CharField(max_length=200, null=True)
    price = models.DecimalField(max_digits=7, decimal_places=2)
    digital = models.BooleanField(default=False, null=True, blank=False)
    image = models.ImageField(null=True, blank=True)
    
    def __str__(self):
        return self.name 
    
    @property
    def imageURL(self):
        try:
            url = self.image.url
        except:
            url = ''
        return url
        
class ProductB(models.Model):
    name = models.CharField(max_length=200, null=True)
    price = models.DecimalField(max_digits=7, decimal_places=2)
    digital = models.BooleanField(default=False, null=True, blank=False)
    image = models.ImageField(null=True, blank=True)
    
    def __str__(self):
        return self.name 
    
    @property
    def imageURL(self):
        try:
            url = self.image.url
        except:
            url = ''
        return url
        
class ProductG(models.Model):
    name = models.CharField(max_length=200, null=True)
    price = models.DecimalField(max_digits=7, decimal_places=2)
    digital = models.BooleanField(default=False, null=True, blank=False)
    image = models.ImageField(null=True, blank=True)
    
    def __str__(self):
        return self.name 
    
    @property
    def imageURL(self):
        try:
            url = self.image.url
        except:
            url = ''
        return url
        
class ProductW(models.Model):
    name = models.CharField(max_length=200, null=True)
    price = models.DecimalField(max_digits=7, decimal_places=2)
    digital = models.BooleanField(default=False, null=True, blank=False)
    image = models.ImageField(null=True, blank=True)
    
    def __str__(self):
        return self.name 
    
    @property
    def imageURL(self):
        try:
            url = self.image.url
        except:
            url = ''
        return url        
    
class Order(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.SET_NULL, blank=True, null=True)
    date_ordered = models.DateTimeField(auto_now_add=True)
    complete = models.BooleanField(default=False, null=True, blank=False)
    transaction_id = models.CharField(max_length=200, null=True)
    
    def __str__(self):
        return str(self.id)
    
    @property
    def shipping(self):
        shipping = False
        orderitems = self.orderitem_set.all()
        for i in orderitems:
            if i.product.digital == False:
                shipping = True
        return shipping
    
    @property 
    def get_cart_total(self):
        orderitems = self.orderitem_set.all()
        total = sum([item.get_total for item in orderitems])
        return total
    
    @property
    def get_cart_items(self):
        orderitems = self.orderitem_set.all()
        total = sum([item.quantity for item in orderitems])
        return total
    
class OrderItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, blank=True, null=True)
    order = models.ForeignKey(Order, on_delete=models.SET_NULL, blank=True, null=True)
    quantity = models.IntegerField(default=0, null=True, blank=True)
    date_added = models.DateTimeField(auto_now_add=True) 
    
    @property
    def get_total(self):
        total = self.product.price * self.quantity
        return total

class ShippingAddress(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.SET_NULL, blank=True, null=True)
    order = models.ForeignKey(Order, on_delete=models.SET_NULL, blank=True, null=True)
    address = models.CharField(max_length=200, null=True)
    city = models.CharField(max_length=200, null=True)
    state = models.CharField(max_length=200, null=True)
    zipcode = models.CharField(max_length=200, null=True)
    date_added = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.address   
    
# class Comment(models.Model):
#     post = models.ForeignKey(User, related_name="comments", on_delete=models.CASCADE)
#     name = models.CharField(max_length=255)
#     body = models.TextField()
#     date_added = models.DateTimeField(auto_now_add=True)
    
#     def __str__(self):
#         return '%s - %s' % (self.post.username, self.name)

#uTo-code
class profile(models.Model):
    user = models.OneToOneField(User, on_delete = models.CASCADE)
    name = models.CharField(default = 'Name Surname', max_length = 200, null = True)
    title = models.CharField(default = 'This is the default, title change it in profile.', max_length = 200, null = True)
    desc_text = 'Hey, there this a default text description about you that you can change on after clicking on "Edit" or going'
    desc  = models.CharField(default = desc_text, max_length = 200, null = True)
    profile_img = models.ImageField(default = 'media/default.jpg', upload_to = 'media', null = True, blank = True)

    def __str__(self):
        return f"{self.user.username}'s profile"
#/uTo-code

gallery/store/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from .models import profile
from django.forms.models import ModelForm

from django.forms.widgets import FileInput


class CreateUserForms(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


class ProfileForm(ModelForm):
    class Meta:
        model = profile
        fields = '__all__'
        exclude = ['user']
        widgets = {
            'profile_img': FileInput(),
        }
        
#Customer.objects.create(User = request.user)

gallery/store/views.py
from email import message
import email
from math import prod
from django.shortcuts import render, redirect
from django.http import JsonResponse
import json
import datetime
from .models import *
from .utils import cookieCart, cartData, guestOrder
from django.core.mail import send_mail,mail_admins, EmailMessage
from django.conf import settings
from django.template.loader import render_to_string

#uTo-code-import
from .forms import CreateUserForms, ProfileForm
from django.contrib import messages
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from .decorators import unauthenticated_user

#uTo-code-import

def store(request):
    data = cartData(request)
    
    cartItems = data['cartItems']
        
    products = Product.objects.all()
    # comments = Comment.objects.all()
    context = {'products': products, 'cartItems':cartItems}
    # context = {'products': products, 'cartItems':cartItems, 'post': comments}
    return render(request, 'store/store.html', context)

def cart(request):
    data = cartData(request)
    
    cartItems = data['cartItems']
    order = data['order']
    items = data['items']
    
    context = {'items':items, 'order': order, 'cartItems':cartItems}
    return render(request, 'store/cart.html', context)

def checkout(request):
    data = cartData(request)
    
    cartItems = data['cartItems']
    order = data['order']
    items = data['items']
        
    context = {'items':items, 'order': order, 'cartItems':cartItems}
    return render(request, 'store/checkout.html', context)

def location(request):
    return render(request, 'store/location.html')

def collections(request):
    data = cartData(request)
    
    cartItems = data['cartItems']
        
    products = Product.objects.all()
    context = {'products': products, 'cartItems':cartItems}
    return render(request, 'store/collections.html', context)

def contacts(request):
    if request.method == "POST":
        name = request.POST['name']
        email = request.POST['email']
        message = request.POST['message']
        print(email + " " + message)
        # send_mail('Contact Form', 
        #           message,
        #           email, 
        #           ['avatar.gallery@mail.ru'], 
        #           fail_silently=False)
        mail_admins("Email Address: " + email + " From: " + name, 
                  message, 
                  fail_silently=False)
    return render(request, 'store/contacts.html')

def about(request):
    return render(request, 'store/about.html')

def updateItem(request):
    data = json.loads(request.body)
    productId = data['productId']
    action = data['action']
    
    print('Action:', action)
    print('productId:', productId)
    
    customer = request.user.customer
    product = Product.objects.get(id=productId)
    order, created = Order.objects.get_or_create(customer=customer, complete=False)
    
    orderItem, created = OrderItem.objects.get_or_create(order=order, product=product)
    
    if action == 'add':
        orderItem.quantity = (orderItem.quantity + 1)
    elif action == 'remove':
        orderItem.quantity = (orderItem.quantity - 1)
        
    orderItem.save()
    
    if orderItem.quantity <= 0:
        orderItem.delete()
    
    return JsonResponse('Item was added', safe=False)

def news(request):
    return render(request, 'store/news.html')

def processOrder(request):
    transaction_id = datetime.datetime.now().timestamp()
    data = json.loads(request.body)
    
    if request.user.is_authenticated:
        customer = request.user.customer
        order, created = Order.objects.get_or_create(customer=customer, complete=False)
        
    else:
        customer, order = guestOrder(request, data)
        
    total = float(data['form']['total'])
    order.transaction_id = transaction_id
    
    if total == float(order.get_cart_total):
        order.complete = True
    order.save()
    
    if order.shipping == True:
        ShippingAddress.objects.create(
            customer = customer,
            order = order,
            address = data['shipping']['address'],
            city = data['shipping']['city'],
            state = data['shipping']['state'],
            zipcode = data['shipping']['zipcode'],
        )
    return JsonResponse('Payment complete', safe=False)


#uTo - code
@login_required(login_url='home')
def home(request):
    return render(request, 'store/home.html')

@login_required(login_url='profile')
def profile(request):
    if request.method == 'POST':
        form = ProfileForm(request.POST, request.FILES, instance=request.user.profile)
        if form.is_valid():
            form.save()
            username = request.user.username
            messages.success(request, f'{username}, Your profile is updated.')
            return redirect('/')
    else:
        form = ProfileForm(instance=request.user.profile)
    context = {'form': form}
    return render(request, 'store/profile.html', context)


def login_user(request):
    
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        try:
            user = User.objects.get(username=username)
        except User.DoesNotExist:
            user = None
        if user is not None:
            login(request, user)
            messages.info(request, f'{username}, You are logged in.')
            return redirect("/")
        else:
            messages.info(request, 'Wrong password or username.')
            return redirect('login')   
    return render(request, 'store/login_page.html')


def register_user(request):
    form = CreateUserForms()

    if request.method == 'POST':
        form = CreateUserForms(request.POST)
        if form.is_valid():
            form.save()
            messages.info(request, 'Account is created.')


            name = form.cleaned_data.get('name')
            email = form.cleaned_data.get('email')

            user = form.save(commit=True)
            user.is_active = True
            user.save()


            profile = Customer()
            profile.user = user
            profile.name = name
            profile.email = email
            profile.save()

            return redirect('login')
        else:
            context = {'form': form}
            messages.info(request, 'Invalid credentials.')
            return render(request, 'store/register_page.html', context)

    context = {'form': form}
    return render(request, 'store/register_page.html', context)

@login_required(login_url='login')
def logout_user(request):
    logout(request)
    messages.info(request, 'You logged out successfully')
    return redirect('login')
#/uTo - code
 

# class AddCommentView(CreateView):
#    model = Comment
#    template_name = 'add_comment.html'
#    fields = '__all__' 

# if request.method == "POST":
#        message_name = request.POST['message-name']
#        message_email = request.POST['message-email']
#        message = request.POST['message']
#        print(message_name+" "+"birnarse")
#        send_mail(
#            message_name, # subject
#            message, # message
#            message_email, # from email
#            ['avatar.gallery@mail.ru'], # to email
#        )
        
#        return render(request, 'store/contacts.html', {'message_name': message_name})
#    else:
#        return render(request, 'store/contacts.html', {})

gallery/store/templates/store/add_comment.html
{% extends 'store/main.html' %} 
{% load static %}
{% block content %}
<div class="form-group">
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.media }}
        {{ form.as_p }}
        <button class="btn btn-secondary">Add Comment</button>
</div>

{% endblock content %}

gallery/store/templates/store/cart.html
{% extends 'store/main.html' %} 
{% load static %}
{% block content %}
<a style="margin-left: 20px;font-family: 'Poiret One', cursive; font-size: 18px; text-decoration: none;">In basket: {{cartItems}}</a>
<div class="row">
    <div class="col-lg-12">
        <div class="box-element">
            <a class="btn btn-outline-dark" href="{% url 'store' %}" style="font-family: 'DM Sans', sans-serif; font-size: 18px; background: #CF0000;
            background: linear-gradient(to right, #CF0000 0%, #FF4D94 100%);
            -webkit-background-clip: text;
            -webkit-text-fill-color: transparent;">&#x2190; Continue Shopping</a>
            <br>
            <br>
            <table class="table">
                <tr>
                    <th>
                        <h5 style="font-family: 'DM Sans', sans-serif; font-size: 20px;">Items: <strong style="font-family: 'Raleway', sans-serif; font-size: 18px;">{{order.get_cart_items}}</strong></h5>
                    </th>
                    <th>
                        <h5 style="font-family: 'DM Sans', sans-serif; font-size: 20px;">Total: <strong style="font-family: 'Raleway', sans-serif; font-size: 18px;">${{order.get_cart_total}}</strong></h5>
                    </th>
                    <th>
                        <a style="float:right; margin:5px; font-family: 'DM Sans', sans-serif; font-size: 18px;" class="btn btn-danger" href="{% url 'checkout' %}">Checkout</a>
                    </th>
                </tr>
            </table>
        </div>

        <br>
        <div class="box-element">
            <div class="cart-row">
                <div style="flex:2"></div>
                <div style="flex:2; font-family: 'DM Sans', sans-serif; font-size: 18px; background: #CF0000;
                background: linear-gradient(to right, #CF0000 0%, #C170FF 100%);
                -webkit-background-clip: text;
                -webkit-text-fill-color: transparent;"><strong>Item</strong></div>
                <div style="flex:1; font-family: 'DM Sans', sans-serif; font-size: 18px; background: #CF0000;
                background: linear-gradient(to right, #CF0000 0%, #C170FF 100%);
                -webkit-background-clip: text;
                -webkit-text-fill-color: transparent;"><strong>Price</strong></div>
                <div style="flex:1; font-family: 'DM Sans', sans-serif; font-size: 18px; background: #CF0000;
                background: linear-gradient(to right, #CF0000 0%, #C170FF 100%);
                -webkit-background-clip: text;
                -webkit-text-fill-color: transparent;"><strong>Quantity</strong></div>
                <div style="flex:1; font-family: 'DM Sans', sans-serif; font-size: 18px; background: #CF0000;
                background: linear-gradient(to right, #CF0000 0%, #C170FF 100%);
                -webkit-background-clip: text;
                -webkit-text-fill-color: transparent;"><strong>Total</strong></div>
            </div>

            {% for item in items %}
            <div class="cart-row">
                <div style="flex:2"><img class="row-image" src={{item.product.imageURL}}></div>
                <div style="flex:2; font-family: 'Poiret One', cursive; font-size: 18px;">{{item.product.name}}</div>
                <div style="flex:1; font-family: 'Poiret One', cursive; font-size: 18px;">${{item.product.price}}</div>
                <div style="flex:1">
                    <p class="quantity" style="font-family: 'Poiret One', cursive; font-size: 18px;">{{item.quantity}}</p>
                    <div class="quantity">
                        <img data-product="{{item.product.id}}" data-action="add" class="chg-quantity update-cart" src="{% static  'images/up.jpg' %}">
                        <img data-product="{{item.product.id}}" data-action="remove" class="chg-quantity update-cart" src="{% static  'images/down.jpg' %}">
                    </div>
                </div>
                <div style="flex:1; font-family: 'Poiret One', cursive; font-size: 18px;"><p>${{item.get_total}}</p></div>
            </div>
            {% endfor %}
        </div>
    </div>
{% endblock content %}

gallery/store/templates/store/collections.html
{% extends 'store/main.html' %} 
{% load static %}
{% block content %}
<div class="row">
    {% for product in products %}
    <div class="col-lg-4" style="padding-bottom: 15px; padding-left: 15px; padding-right: 15px; font-family: 'Quicksand', sans-serif;">
        <img class="thumbnail" src="{{product.image.url}}" width="320px">
        <div class="box-element product">
            <h6 style="margin-top: 15px; font-family: 'DM Sans', sans-serif; font-size: 18px;"><strong>{{product.name}}</strong></h6>
            <hr>
            <button data-product={{product.id}} data-action="add" class="btn btn-outline-secondary add-btn update-cart" onClick="showMessage()">To Basket</button>
            <a class="btn btn-outline-danger" href="{% url 'cart' %}">View</a>
            <h4 style="display: inline-block; margin-left: 170px; font-family: 'DM Sans', sans-serif; font-size: 18px;"><strong>${{product.price}}</strong></h4>
        </div>
    </div>
    {% endfor %}
</div>
<hr>

{% endblock content %}

gallery/store/templates/store/contacts.html
{% extends 'store/main.html' %} 
{% load static %}
{% block content %}

<div style="display: flex;">
    <img src="{% static  'images/contactsimg.jpeg' %}" width="500px" height="400px" style="margin-left: 120px; margin-right: 200px; margin-top: 30px;">
    <div>
        
        <form action="{% url 'contacts' %}" method="POST">
            {% csrf_token %}  
            <input name="name" type="text" placeholder="Name" style="font-size: 17px; font-family: 'Quicksand', sans-serif; margin-bottom: 20px; margin-top: -5px;">   
            <input name="email" type="text" placeholder="Email" style="font-size: 17px; font-family: 'Quicksand', sans-serif; margin-bottom: 20px;">
            <textarea name="message" placeholder="Message" style="font-size: 17px; font-family: 'Quicksand', sans-serif; margin-bottom: 20px;"></textarea>
            <input type="submit" value="Send Message" style="font-size: 30px; font-family: 'Quicksand', sans-serif;">
        </form>
    </div>
</div>

{% endblock content %}

gallery/store/templates/store/login_page.html
{% extends 'store/main.html' %}
{% load static %}
{% block content %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    
    <link href="https://fonts.googleapis.com/css2?family=Nunito:ital,wght@0,200;0,300;0,400;0,600;0,700;0,800;0,900;1,200;1,300;1,400;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'css/profile.css' %}">
    <link rel="stylesheet" href="{% static 'css/register.css' %}">
    <link rel="stylesheet" href="{% static 'css/login.css' %}">

    <title>Login Page</title>

    <style>
      button {
        background: rgb(252,69,69);
        background: linear-gradient(37deg, rgba(252,69,69,1) 0%, rgba(252,69,120,1) 100%);
      }
  </style>
  </head>
  <body>

  {% if messages %}
    <div class="notification-container">
        <div class="notification">
            {% for message in messages %}
            <p {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</p>
            {% endfor %}
            <img id='cross' src="{% static 'images/close.png' %}" width="15px" height="15px" alt="">
        </div>
    </div>
    <script>
        var cross = document.getElementById('cross')
        cross.addEventListener('click', ()=> {
            document.getElementsByClassName('notification-container')[0].style.display = 'none';
        })
    </script>
  {% endif %}

    <main class="main-container" style="font-family: 'Quicksand', sans-serif;">
        <div class="container " style="margin-left: 400px;">
          <h1 class="signup-heading" style="margin-top: -30px; margin-left: 265px; font-size: 28px;">Log in</h1>
            <div class="user-content-container user-profile-form-container">
              <form action="" method="POST" style="margin-top: -20px; margin-left: -20px;">
                  {% csrf_token %}
                  <ul>
                  <li class="name">
                      <label for="username">Username</label>
                      <input type="text" name="username" id="username" class="username-input" placeholder="Username">
                  </li>
                  <li class="pass">
                    <label for="">Password</label>
                    <input type="password" name = "password" id="password" class="pass-input" placeholder="Password">
                  </li>
                    <button class="signup-button" style="margin-left: 60px;"> Log in </button>
                    <p class="login-link" style="margin-top: 30px; margin-left: 120px;">Don't have an account?? <a href="{% url 'register' %}">Sign Up</a></p>
                  </ul>
              </form>
            </div>
        </div>
    </main>

    {% comment %} background: rgb(252,69,69);
          background: linear-gradient(37deg, rgba(252,69,69,1) 0%, rgba(69,151,252,1) 100%); {% endcomment %}

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.min.js" integrity="undefined" crossorigin="anonymous"></script>
  </body>
</html>
    
{% endblock content %}

gallery/store/templates/store/profile.html
{% extends 'store/main.html' %}
{% load static %}
{% block content %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">


    <link href="https://fonts.googleapis.com/css2?family=Nunito:ital,wght@0,200;0,300;0,400;0,600;0,700;0,800;0,900;1,200;1,300;1,400;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'css/profile.css' %}">

    <title>Profile</title>

    <style>
        #note {
            position: absolute;
            z-index: 101;
            top: 0;
            left: 0;
            right: 0;
            text-align: center;
            line-height: 2.5;
            overflow: hidden;
            -webkit-box-shadow: 0 0 5px black;
            -moz-box-shadow: 0 0 5px black;
            box-shadow: 0 0 5px black;
        }
        
        .profile-icon-link-container div {
            display: block;
            background: rgb(252, 69, 69);
            background: linear-gradient(37deg, rgba(252, 69, 69, 1) 0%, rgba(252, 69, 120, 1) 100%);
            padding: 10px 30px;
            border-radius: 2px;
            color: white;
            text-align: center;
            width: 200px;
            margin-left: 188px;
        }
        
        .profile-page-heading {
            font-size: 2em;
            margin-bottom: 1em;
        }
        
        .profile-photo-form-container {
            width: 50%;
        }
        
        .profile-photo-container button {
            margin-top: 1.5em;
            width: 70%;
            padding: .8em;
            background-color: #FFD13A;
            border: none;
            border-radius: 3px;
            font-size: 1em;
            font-weight: 600;
        }
        
        #id_profile_img {
            width: 70% - 1.6em;
            padding: .8em .8em;
            margin-top: 1.5em;
            width: 70%;
            padding: .8em;
            background-color: #FFD13A;
            border: none;
            border-radius: 3px;
            font-size: 1em;
            font-weight: 600;
            cursor: pointer;
        }
        
        .user-profile-form-container {
            width: 60%;
            margin: 2em;
            padding: 0;
        }
        
        .user-content-container ul {
            list-style-type: none;
            display: flex;
            flex-direction: column;
            width: 100%;
            justify-content: center;
        }
        
        .user-content-container ul li {
            display: flex;
            flex-direction: column;
            width: 100%;
        }
        
        .user-profile-form-container label {
            font-size: larger;
            width: 100%;
            margin: .5em auto .3em 0;
        }
        
        .user-profile-form-container input {
            width: 100%-14px;
            height: 2.5em;
            border-radius: 3px;
            border: solid #707070 1px;
            margin: .1em 0;
            padding: 0 7px;
        }
        
        .profile-save-button {
            margin-top: 1.5em;
            width: 40%;
            padding: .8em;
            border: none;
            border-radius: 5px;
            font-size: 1em;
            font-weight: 600;
            cursor: pointer;
        }
        
        .profile-logout-button {
            margin-top: 1.5em;
            width: 40%;
            padding: .8em;
            border: none;
            border-radius: 5px;
            font-size: 1em;
            font-weight: 600;
            cursor: pointer;
        }
        
        @media only screen and (max-width: 1200px) {
            .container {
                display: block;
                margin-left: .1em;
                margin-right: .1em;
            }
            .main-container {
                padding: 2em 1.5em;
            }
            .user-profile-form-container {
                padding-left: 0;
                margin: 2em auto;
                width: 90%;
            }
            .profile-photo-container {
                width: 100%;
            }
        }
        
        @media only screen and (max-width: 600px) {
            .user-profile-form-container {
                margin: 2em auto;
            }
            .user-title {
                width: 100%;
            }
            .main-container {
                margin: 10% auto;
                width: 80%;
            }
            .header-username {
                display: none;
            }
            .profile-photo-container {
                width: 100%;
            }
        }
        button {
            background: rgb(252,69,69);
            background: linear-gradient(37deg, rgba(252,69,69,1) 0%, rgba(252,69,120,1) 100%);
        }
    </style>
  </head>
  <body>
    <main class="main-container" style="font-family: 'Quicksand', sans-serif;">
            <form class = 'container' action="" method="POST" enctype="multipart/form-data">
                {% csrf_token %}<div style="display: flex;"><div class="profile-photo-container profile-photo-form-container" style="margin-left: 60px;">
                    <p class="profile-page-heading" style="margin-left: 70px; ">Edit your profile</p>
                    <img src="{{user.profile.profile_img.url}}" alt="user-image" width="300" srcset="" style="margin-left: 30px;">
                    {{form.profile_img}}
                </div>


                <div class="user-content-container user-profile-form-container">
                    <ul>
                        <li class="name">
                            <label for="user-name">Your Name</label>
                            {{form.name}}
                        </li>
                        <li class="title">
                            <label for="user-title">Your title</label>
                            {{form.title}}
                        </li>
                        <li class="desc">
                            <label for="user-desc">Description</label>
                            {{form.desc}}
                        </li>
                    </ul>
                    <button class="profile-save-button" onclick="{% url 'home' %}" style="margin-left: 180px; margin-bottom: 15px;">Save</button>
                    <a class="profile-icon-link-container" href="{% url 'login' %}" style="padding: 10px 30px;">
                        <div class="header-logout">Log Out</div>
                    </a> 

                </div>
            </form>
    </main>

    <script>
        var id_name = document.getElementById('id_name')
        var id_title = document.getElementById('id_title')
        var id_desc = document.getElementById('id_desc')
        id_name.placeholder = 'Your Name'
        id_title.placeholder = 'Your Title'
        id_desc.placeholder = 'Description'
    </script>
  </body>
  {% endblock content %}